server:
  port: 8090
spring:
  boot:
    admin:
        client:
         instance:
          name: ignite-server
         url:
         - http://localhost:8091
        
management:
    endpoints:
      web:
        exposure:
          include:
          - httptrace
          - loggers
          - health
          - info
          - metrics
ignite:
  igniteInstanceName: properties-instance-name
  communicationSpi:
    localPort: 5555
  dataStorageConfiguration:
    defaultDataRegionConfiguration:
      initialSize: 10485760 #10MB
    dataRegionConfigurations:
      - name: my-dataregion
        initialSize: 104857600 #100MB
  cacheConfiguration:
    - name: accounts
      queryEntities:
      - tableName: ACCOUNTS
        keyFieldName: ID
        keyType: java.lang.Long
        valueType: java.lang.Object
        fields:
          ID: java.lang.Long
          amount: java.lang.Double
          updateDate: java.util.Date
    - name: my-cache2