server:
  port: 8090
spring:
  boot:
    admin:
        client:
         instance:
          name: ignite-server
         url:
         - http://localhost:8091
management:
    endpoints:
      web:
        exposure:
          include:
          - httptrace
          - loggers
          - health
          - info
          - metrics
ignite:
  ignite-home: D:/XVACloudPOC/CloudUpLift/ignite-server
  work-directory: D:/XVACloudPOC/CloudUpLift/ignite-server/ignite
  ignite-instance-name:  server-node-1
  consistent-id:
    node1
  client-mode: false
  #data-storage-configuration:
   # data-region-configurations:
    # default-data-region-configuration:
     # name: nonPersistantRegion
      #initial-size: 4000000
      #max-size: 5000000
      #persistence-enabled: false
      #cdc-enabled: false
      
    
    
      
        
      