server:
  port: 8095
spring:
  boot:
    admin:
        client:
         instance:
          name: ignite-client
         url:
         - http://localhost:8091
management:
    endpoints:
      web:
        exposure:
          include:
          - httptrace
          - loggers
          - health
          - info
          - metrics
ignite-client:
  addresses: 127.0.0.1:10800 # this is mandatory property!
  timeout: 10000
  tcpNoDelay: false